language: python

python:
  - 2.7
  - 3.4


before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

install:
  - conda create --name testenv --yes python=$TRAVIS_PYTHON_VERSION matplotlib statsmodels pip six nose openpyxl=1.8 pyyaml requests coverage
  - source activate testenv
  - pip install coveralls
  - pip install .
  # - cp test/matplotlibrc .

script:
  - cd ~
  - python -c "import pytemplate; pytemplate.test(verbose=2, coverage=True)"

after_success:
  - coveralls

#conda create --name pytemplate python=3.3 ipython-notebook matplotlib \
#                    statsmodels nose pip pyyaml requests coverage \
#                    sphinx six openpyxl=1.8
